version: "3"
services:
  lumel-app:
      build: .
      ports:
        - "8000:8000"
      image: rathink4/lumel-app
      volumes:
        - ./:/app
        - /app/node_modules
      environment:
        - PORT=8000
      # env_file:
      #   - .env
      # to run mongodb container first, use depends_on
      depends_on:
        - mongodb
    
  mongodb: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rathink4
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_pass3
    volumes:
      - mongo-db:/data/db
    

volumes:
  mongo-db: